<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9cxr562\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9cxr562/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/Container9cxr562.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\Container9cxr562\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \Container9cxr562\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => '9cxr562',
    'container.build_id' => '11ba8ee4',
    'container.build_time' => 1789565372,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9cxr562');
