<?php

namespace Container9cxr562;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_RateLimiterService extends Glpi_Kernel_KernelProductionDebugContainer
{
    /**
     * Gets the public 'cache.rate_limiter' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\FilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Traits/AbstractAdapterTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache-contracts/CacheTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Traits/ContractsTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Adapter/AbstractAdapter.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/PruneableInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Traits/FilesystemCommonTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Traits/FilesystemTrait.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Adapter/FilesystemAdapter.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Marshaller/MarshallerInterface.php';
        include_once \dirname(__DIR__, 5).'/vendor/symfony/cache/Marshaller/DefaultMarshaller.php';

        $instance = new \Symfony\Component\Cache\Adapter\FilesystemAdapter('0-qgV3zmpm', 0, ($container->targetDir.''.'/pools/app'), ($container->privates['cache.default_marshaller'] ??= new \Symfony\Component\Cache\Marshaller\DefaultMarshaller(NULL, true)));

        if ($container->has('logger')) {
            $instance->setLogger(($container->services['logger'] ?? $container->get('logger', 3)));
        }

        return $container->services['cache.rate_limiter'] = $instance;
    }
}
